### ISSUE TITLE
Need to split this even more

### ISSUE THREAD

**Issue by coryan** [conda-forge/google-cloud-cpp-feedstock#164]
### Comment:

#162 required multiple attempts and the last one succeeded with only 20m (out of 360m) to spare.  We need to split this build even more, or otherwise reduce the total build time.

**Comment by h-vetinari** [comment]
Thanks for opening the issue & the timings! In terms of strategies, we should also consider that not everything we peel off must go into a new feedstock, it can also go into any of the existing ones:
* https://github.com/conda-forge/google-cloud-cpp-core-feedstock
* https://github.com/conda-forge/google-cloud-cpp-ai-feedstock
* https://github.com/conda-forge/google-cloud-cpp-bigquery-feedstock
* https://github.com/conda-forge/google-cloud-cpp-compute-feedstock

 The topical grouping of outputs is useful for humans, but it's not a real technical concern (as long as there are no inter-output dependencies, those we obviously need to handle). Of course, I'd like to keep the grouping sensible, but we should just keep that possibility in mind.

**Comment by coryan** [comment]
> we should also consider that not everything we peel off must go into a new feedstock, it can also go into any of the existing ones:

Absolutely.  

I did run into problems trying to build a lot of sub-packages in `google-cloud-cpp-ai-feedstock`.  Eventually I just [reduced the number of subpackages](https://github.com/conda-forge/staged-recipes/pull/24843#issuecomment-1879746243). See (for examples) https://github.com/conda-forge/staged-recipes/pull/24843/commits/51e09f6c3de7d7342e56f4fe9e1b237f19a84a64 

That may have been a limitation of the staged recipes repository.  Or something I mistyped.  I think it is worthwhile growing the existing feedstocks, but we should be aware of this potential pitfall.

**Comment by coryan** [comment]
FWIW, #165 looks promising.  The CI completed under 5 hours.  I expect the build time will go up again once the `-core-feedstock` gets more subpackages and I change #165 to depend on them, but hopefully not by another hour.

@h-vetinari any problems if we merge https://github.com/conda-forge/google-cloud-cpp-core-feedstock/pull/11 and then merge #165 (with the right additions)?

**Comment by h-vetinari** [comment]
> @h-vetinari any problems if we merge [conda-forge/google-cloud-cpp-core-feedstock#11](https://github.com/conda-forge/google-cloud-cpp-core-feedstock/pull/11) and then merge #165 (with the right additions)?

Sounds like a plan! Go for it!

**Comment by coryan** [comment]
After #165 the slowest build took 5h31m.  Still fairly tight.  The next thing to move is `retail` and other large features to `google-cloud-cpp-ai-feedstock`.

Interestingly, the slowest builds on #170 are not the same builds that are slow on #165.

**Comment by h-vetinari** [comment]
> Interestingly, the slowest builds on #170 are not the same builds that are slow on #165.

Azure pipelines has at least two different kind of agents, and the weaker kind is roughly 50% slower than the faster one. On OSX there's also some rare agents that take 3-4x as long as the regular ones.

**Comment by coryan** [comment]
> Azure pipelines has at least two different kind of agents, and the weaker kind is roughly 50% slower than the faster one. On OSX there's also some rare agents that take 3-4x as long as the regular ones.

I expected something like that.  It just makes it hard to convince myself an improvement is real.

I any case, with #171 the build times are under 5 hours.  I think we can close this bug once that gets merged.  I do expect we will need to rebalance things from time to time.

@dbolduc any plans to enable OTel should consider some time spent rebalancing the builds.  We can create new feedstocks if needed, or use `-compute` for other compute services (e.g. appengine, cloud run, and cloud batch, cloud TPU, anything GKE related are arguably about configuring compute resources).
