### ISSUE TITLE
Update README file

### ISSUE THREAD

**Issue by coryan** [conda-forge/google-cloud-cpp-feedstock#166]
### Comment:

The README file does not list the `*-devel` package, and lists older packages too.

**Comment by xhochy** [comment]
The README is autogenerated from the content in `meta.yaml`. If you want to mention the `*-devel` packages in other repositories, you would need to mention that in the `description` section.

**Comment by coryan** [comment]
I looked at this yesterday and missed the changes in #162. Closing.
