### ISSUE TITLE
nlohmann_json needed for using google-cloud-cpp via cmake in 1.17.0+

### ISSUE THREAD

**Issue by kkraus14** [conda-forge/google-cloud-cpp-feedstock#28]
Issue: As of google-cloud-cpp 1.17.0+, using it via cmake does a search for `nlohmann_json` and errors if not found. Should this be specified as a runtime dependency or is it the user's responsibility to add the `nlohmann_json` package as well?

Relevant PR: https://github.com/googleapis/google-cloud-cpp/pull/4747

**Comment by xhochy** [comment]
Yes, this definitely should be a `run` dependency. It would be nice to have a small compile test in the `tests` section to verify in future that such things aren't missing.

@kkraus14 Also feel free to add yourself as a maintainer. I've only added this package to conda-forge as we planned to use in it Arrow but don't have done so far, thus it's quite low on my priority list.

**Comment by xhochy** [comment]
Fixed by #83
